# Define base image
FROM continuumio/miniconda3

# Set working directory for the project
WORKDIR /app

# Create Conda environment from the YAML file
COPY requirement.yml .
RUN conda env create -f requirement.yml

ENV PATH /opt/conda/envs/AI/bin:$PATH
RUN /bin/bash -c "source activate AI"
